---

- name:             get passwd lock info for vagrant
  command:          passwd -S vagrant
  register:         passwd_vagrant
  changed_when:     false

- name:             lock password for vagrant
  command:          passwd -l vagrant
  when:             passwd_vagrant.stdout.split()[1][0] != 'L'

- name:             disable SSH Password Authentication login
  lineinfile:       destfile=/etc/ssh/sshd_config regexp="^PasswordAuthentication" line="PasswordAuthentication no" state=present
  notify:
    - restart ssh

- name:             change SSH PermitRootLogin from without-password to no
  lineinfile:       destfile=/etc/ssh/sshd_config regexp="^PermitRootLogin" line="PermitRootLogin no" state=present
  notify:
    - restart ssh
