---

- name:             get apt key for dotnet
  copy:             dest=/root/cache/417A0893.asc src=dotnetdev.asc
                    owner=root group=root mode=0644

- name:             install apt key for dotnet
  apt_key:          id=417A0893 file=/root/cache/417A0893.asc state=present

- name:             sources.list.d for dotnet
  template:         dest=/etc/apt/sources.list.d/dotnetdev.list src=dotnetdev.list
                    owner=root group=root mode=0644
  register:         dotnet_sources

- name:             preferences.d for dotnet
  copy:             dest=/etc/apt/preferences.d/dotnetdev.pref src=dotnetdev.pref
                    owner=root group=root mode=0644

- name:             update apt cache
  apt:              update_cache=yes
  when:             dotnet_sources is changed

- name:             install dotnet-dev package
  apt:              name={{ item }} state=present
  with_items:
    - "{{ pkgs_dotnet }}"
