---

#- name:             check if xpack was installed allready
#  stat:             path=/usr/share/logstash/vendor/bundle/jruby/2.3.0/gems/x-pack-6.2.4-java/x-pack.gemspec
#  register:         logstash_xpack_check
#  changed_when:     false

#- name:             ensure logstash is stopped before installing xpack
#  service:          name=logstash state=stopped enabled=yes
#  when:             logstash_xpack_check.stat.exists == false

- name:             install xpack plugin for logstash
  become_user:      logstash
  shell:            bin/logstash-plugin install x-pack
                    chdir=/usr/share/logstash
                    creates=/usr/share/logstash/vendor/bundle/jruby/2.3.0/gems/x-pack-6.2.4-java/x-pack.gemspec
  register:         logstash_xpack_install
