---

- include_tasks:    logstash-install_debian-based.yml
  when:             pkgs_logstash is defined and (ansible_distribution == "Ubuntu" or ansible_distribution == "Debian")

- include_tasks:    logstash-install_xpack.yml
  when:             elk_stack_use_xpack

- include_tasks:    logstash-configure.yml
