---

- include_tasks:    logstash-install_debian-based.yml
  when:             pkgs_logstash is defined and (ansible_distribution == "Ubuntu" or ansible_distribution == "Debian")

- include_tasks:    logstash-install_general.yml
