---

- name:             disable default nginx site
  file:             path=/etc/nginx/conf.d/ state=absent
  notify:           restart nginx

- name:             create nginx config folders
  file:             path=/etc/nginx/{{ item }} state=directory mode=0755
  notify:           restart nginx
  register:         fix_nginx
  with_items:
    - sites-available
    - sites-enabled

- name:             fix nginx.conf
  copy:             dest=/etc/nginx/nginx.conf src=nginx.conf.redhat-based mode=0644
  notify:           restart nginx
  when:             fix_nginx is changed

- name:             Allow http/https traffic through Firewalld
  firewalld:        service={{ item }} permanent=true state=enabled
  with_items:
    - "{{ ports }}"
