---

- name:             disable default nginx site
  file:             path=/etc/nginx/sites-enabled/default state=absent
  notify:           restart nginx

- name:             comment out ssl settings we handle in _ssl.conf (1)
  lineinfile:       dest=/etc/nginx/nginx.conf
                    regexp='^\t(ssl_protocols.*)' line='\t# \1' backrefs=yes
  notify:           restart nginx

- name:             comment out ssl settings we handle in _ssl.conf (2)
  lineinfile:       dest=/etc/nginx/nginx.conf
                    regexp='^\t(ssl_prefer_server_ciphers.*)' line='\t# \1' backrefs=yes
  notify:           restart nginx

- name:             comment out gzip we handle in _ssl.conf (1)
  lineinfile:       dest=/etc/nginx/nginx.conf
                    regexp='^\t(gzip on;)' line='\t# \1' backrefs=yes
  notify:           restart nginx

- name:             comment out gzip we handle in _ssl.conf (2)
  lineinfile:       dest=/etc/nginx/nginx.conf
                    regexp='^\t(gzip_disable "msie6";)' line='\t# \1' backrefs=yes
  notify:           restart nginx

- name:             Allow http/https traffic through UFW
  ufw:              rule=allow port={{ item }} proto=tcp
  with_items:
    - "{{ nginx_ports }}"
