---

# Add the PPA off the maintainer of Debian's PHP packages, Ond?ej Sur?.
# This allows nginx 1.12 to be installed
# See more : https://deb.sury.org/

- name:             add ppa:ondrej/nginx
  apt_repository:   repo='ppa:ondrej/nginx'
                    state=present
                    update_cache=yes
  register:         nginx_ppa

- name:             update system
  apt:              upgrade=safe
  when:             nginx_ppa.changed

- name:             install nginx packages
  apt:              name={{ item }} state=present install_recommends=no
  with_items:
    - "{{ pkgs_nginx }}"

- name:             touch nginx in /root/stat_services.d
  file:             path=/root/stat_services.d/nginx state=touch
  changed_when:     false

- name:             disable default nginx site
  file:             path=/etc/nginx/sites-enabled/default state=absent
  notify:           restart nginx

- name:             comment out ssl settings we handle in _ssl.conf (1)
  lineinfile:       dest=/etc/nginx/nginx.conf
                    regexp='^\t(ssl_protocols.*)' line='\t# \1' backrefs=yes
  notify:           restart nginx

- name:             comment out ssl settings we handle in _ssl.conf (2)
  lineinfile:       dest=/etc/nginx/nginx.conf
                    regexp='^\t(ssl_prefer_server_ciphers.*)' line='\t# \1' backrefs=yes
  notify:           restart nginx

- name:             comment out gzip we handle in _ssl.conf (1)
  lineinfile:       dest=/etc/nginx/nginx.conf
                    regexp='^\t(gzip on;)' line='\t# \1' backrefs=yes
  notify:           restart nginx

- name:             comment out gzip we handle in _ssl.conf (2)
  lineinfile:       dest=/etc/nginx/nginx.conf
                    regexp='^\t(gzip_disable "msie6";)' line='\t# \1' backrefs=yes
  notify:           restart nginx

- name:             create directory /etc/devops/www
  file:             path=/etc/devops/www state=directory mode=0755

- name:             ensure /etc/devops/ssl exists and is secure
  file:             path=/etc/devops/ssl state=directory owner=root group=root mode=0700

- name:             place /etc/devops/www/index.html
  copy:             dest=/etc/devops/www/index.html src=index.html mode=0644

- name:             place /etc/devops/www/502.html
  copy:             dest=/etc/devops/www/502.html src=502.html mode=0644

- name:             place /etc/devops/ssl/dhparams.pem
  copy:             dest=/etc/devops/ssl/dhparams.pem src=dhparams.pem owner=root group=root mode=0600

- name:             place /etc/devops/ssl/dhparams.4096.pem
  copy:             dest=/etc/devops/ssl/dhparams.4096.pem src=dhparams.4096.pem owner=root group=root mode=0600

- name:             place /etc/nginx/sites-available/_default.conf
  copy:             dest=/etc/nginx/sites-available/_default.conf src=_default.conf mode=0644
  notify:           restart nginx

- name:             link _default.conf to /etc/nginx/sites-enabled/
  file:             path=/etc/nginx/sites-enabled/_default.conf src=/etc/nginx/sites-available/_default.conf state=link
  notify:           restart nginx

- name:             place /etc/nginx/sites-available/_logformats.conf
  copy:             dest=/etc/nginx/sites-available/_logformats.conf src=_logformats.conf mode=0644
  notify:           restart nginx

- name:             link _logformats.conf to /etc/nginx/sites-enabled/
  file:             path=/etc/nginx/sites-enabled/_logformats.conf src=/etc/nginx/sites-available/_logformats.conf state=link
  notify:           restart nginx

- name:             place /etc/nginx/sites-available/_ssl.conf
  copy:             dest=/etc/nginx/sites-available/_ssl.conf src=_ssl.conf mode=0644
  notify:           restart nginx

- name:             link _ssl.conf to /etc/nginx/sites-enabled/
  file:             path=/etc/nginx/sites-enabled/_ssl.conf src=/etc/nginx/sites-available/_ssl.conf state=link
  notify:           restart nginx
