---

- include_tasks:    install_debian-based.yml
  when:             ansible_distribution == "Ubuntu" or ansible_distribution == "Debian"

- include_tasks:    install_redhat-based.yml
  when:             ansible_distribution == "CentOS" or ansible_distribution == "RedHat"

- include_tasks:    configure_debian-based.yml
  when:             ansible_distribution == "Ubuntu" or ansible_distribution == "Debian"

- include_tasks:    configure_redhat-based.yml
  when:             ansible_distribution == "CentOS" or ansible_distribution == "RedHat"

- include_tasks:    configure_general.yml
