---

# Add the PPA off the maintainer of Debian's PHP packages, Ond?ej Sur?.
# This allows multiple php versions to be installed in tandem
# See more : https://deb.sury.org/


- name:             add ppa:ondrej/php
  apt_repository:   repo='ppa:ondrej/php'
                    state=present
                    update_cache=yes
  register:         phpfpm_ppa

- name:             update system
  apt:              upgrade=safe
  when:             phpfpm_ppa.changed

- name:             install php-fpm
  apt:              name={{ item }} state=present install_recommends=no
  notify:           restart php-fpm
  register:         phpfpm_install
  with_items:
    - "{{ pkgs_phpfpm }}"

- name:             update www.conf
  lineinfile:       dest="/etc/php/7.2/fpm/pool.d/www.conf"
                    state=present
                    regexp=^{{ item.key }}
                    line="{{ item.value }}"
                    insertafter=EOF backrefs=yes
  when:             phpfpm_install is changed
  notify:           restart php-fpm
  with_items:
    - { key: 'listen = /run/php/php7.2-fpm.sock', value: 'listen = /run/php7.2-fpm.sock' }

