---

- name:             install remi-php repo
  yum:              name=http://rpms.remirepo.net/enterprise/remi-release-7.rpm state=present

- name:             install php-fpm
  yum:              name={{ item }} state=present enablerepo="remi-php72"
  register:         phpfpm_install
  with_items:
    - "{{ pkgs_phpfpm }}"

- name:             create directories
  file:
    path:  "{{ item.path }}"
    state: directory
    owner: "{{ item.owner }}"
    group: "{{ item.group }}"
    mode:  "{{ item.mode }}"
  with_items:
    - { owner: "nginx", group: "nginx", path: "/run/php", mode: "0755" }
    - { owner: "root", group: "nginx", path: "/var/opt/remi/php72/lib/php/opcache", mode: "0775" }
    - { owner: "root", group: "nginx", path: "/var/opt/remi/php72/lib/php/session", mode: "0775" }
    - { owner: "root", group: "nginx", path: "/var/opt/remi/php72/lib/php/wsdlcache", mode: "0775" }

- name:             update www.conf
  lineinfile:       dest="/etc/opt/remi/php72/php-fpm.d/www.conf"
                    state=present
                    regexp=^{{ item.key }}
                    line="{{ item.value }}"
                    insertafter=EOF backrefs=yes
  when:             phpfpm_install is changed
  with_items:
    - { key: 'user = apache', value: 'user = nginx' }
    - { key: 'group = apache', value: 'group = nginx' }
    - { key: 'listen = 127.0.0.1:9000', value: 'listen = /run/php/php7.2-fpm.sock' }
    - { key: ';listen.owner = nobody', value: 'listen.owner = nginx' }
    - { key: ';listen.group = nobody', value: 'listen.group = nginx' }
    - { key: ';listen.mode = 0660', value: 'listen.mode = 0664' }

- name:             link php to php72
  file:             path=/usr/bin/php src=/opt/remi/php72/root/usr/bin/php state=link

- name:             ensure php-fpm service is enabled
  service:          name=php72-php-fpm state=restarted enabled=yes
