---

- name:             ruby
  hosts:            "{{ targets }}"
  gather_facts:     no
  become:           true
  become_user:      root

  roles:
    - ruby
    - { role: chruby, when: ansible_hostname == 'vm-ubuntu'}
