---

- name:             fetch server IP
  shell:            ifconfig | egrep -o '([0-9]{1,3}\.){3}[0-9]{1,3}' | egrep -v '255|10|(127\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3})' | head -n1
  register:         frox_ip
  failed_when:      false
  changed_when:     false

- name:             set facts specific to redhat-based distros
  set_fact:
    scl_mariadb:   "scl enable rh-mariadb102 --"
    service_phpfpm_name: php72-php-fpm
    frox_mysql_socket: "/var/lib/mysql/mysql.sock"
    frox_httpd_user:  nginx
    frox_httpd_group: nginx
    proftpd_user:     nobody
    proftpd_group:    nobody
    proftpd_modules:  /usr/libexec/proftpd/

- name:             disable check-files configs in nscd
  lineinfile:       path=/etc/nscd.conf
                    state=present
                    backrefs=yes
                    regexp=^{{ item.key }}
                    line="{{ item.key }}{{ item.value }}"
  with_items:
    - { key: "\tcheck-files\t\tpasswd\t\t", value: 'no' }
    - { key: "\tcheck-files\t\tgroup\t\t", value: 'no' }
    - { key: "\tcheck-files\t\thosts\t\t", value: 'no' }
    - { key: "\tcheck-files\t\tservices\t", value: 'no' }
    - { key: "\tenable-cache\t\tnetgroup\t", value: 'no' }
    - { key: "\tcheck-files\t\tnetgroup\t", value: 'no' }
  notify:
    - restart nscd

- name:             create /etc/nginx/conf-enabled/ when ssl is enabled
  file:             path=/etc/nginx/conf-enabled/ state=directory owner=root group=root mode=0755
  when:             frox_use_ssl == true

- name:             template /etc/nginx/conf-enabled/acme.conf when ssl is enabled
  template:
    src:            acme.conf.j2
    dest:           /etc/nginx/conf-enabled/acme.conf
    owner:          root
    group:          root
    mode:           0644
  when:             frox_use_ssl == true

- name:             template /etc/libnss-mysql.cfg
  template:
    src:            libnss-mysql.cfg.j2
    dest:           /etc/libnss-mysql.cfg
    owner:          nscd
    group:          nscd
    mode:           0600
    backup:         yes
  notify:           restart nscd

- name:             template /etc/libnss-mysql-root.cfg
  template:
    src:            libnss-mysql-root.cfg.j2
    dest:           /etc/libnss-mysql-root.cfg
    owner:          nscd
    group:          nscd
    mode:           0600
    backup:         yes
  notify:           restart nscd

- name:             copy /etc/nsswitch.conf
  copy:
    src:            nsswitch.conf
    dest:           /etc/nsswitch.conf
    owner:          root
    group:          root
    mode:           0644
    backup:         yes

- name:             ensure /etc/proftpd/ exists
  file:             path=/etc/proftpd/ state=directory owner=root group=root mode=0755

- name:             template /etc/proftpd.conf
  template:
    src:            proftpd.conf.j2
    dest:           /etc/proftpd.conf
    owner:          root
    group:          root
    mode:           0600
  notify:           restart proftpd

- name:             template /etc/proftpd/modules.conf
  template:
    src:            modules.conf.j2
    dest:           /etc/proftpd/modules.conf
    owner:          root
    group:          root
    mode:           0644
  notify:           restart proftpd

- name:             template /etc/proftpd/sql.conf
  template:
    src:            sql.conf.j2
    dest:           /etc/proftpd/sql.conf
    owner:          root
    group:          root
    mode:           0600
  notify:           restart proftpd

- name:             template /etc/proftpd/tls.conf
  template:
    src:            tls.conf.j2
    dest:           /etc/proftpd/tls.conf
    owner:          root
    group:          root
    mode:           0644
  notify:           restart proftpd
  when:             frox_use_ssl == true

- name:             template /etc/nginx/nginx.conf
  template:
    src:            nginx.conf.j2
    dest:           /etc/nginx/nginx.conf
    owner:          root
    group:          root
    mode:           0664
  notify:           restart nginx

- name:             template /etc/nginx/sites-available/_upstreams.conf
  template:
    src:            nginx.upstreams.conf.j2
    dest:           /etc/nginx/sites-available/_upstreams.conf
    owner:          root
    group:          root
    mode:           0664

- name:             symlink _upstreams.conf
  file:             src=/etc/nginx/sites-available/_upstreams.conf
                    dest=/etc/nginx/sites-enabled/_upstreams.conf
                    state=link
  notify:           restart nginx

- name:             template /etc/opt/remi/php72/default.conf
  template:
    src:            php-fpm.default.conf.j2
    dest:           /etc/opt/remi/php72/default.conf
    owner:          root
    group:          root
    mode:           0664
  notify:           restart php-fpm

- name:             update /etc/opt/remi/php72/php-fpm.conf to load default.conf
  lineinfile:       dest=/etc/opt/remi/php72/php-fpm.conf
                    insertafter='^include=/etc/opt/remi/php72/php-fpm.d/*.conf'
                    line='include=/etc/opt/remi/php72/default.conf'
                    state=present
  notify:           restart php-fpm

- name:             create systemd folders
  file:
    path:  "{{ item.path }}"
    state: directory
    owner: "{{ item.owner }}"
    group: "{{ item.group }}"
    mode:  "{{ item.mode }}"
  register:         systemd_folders
  with_items:
    - { owner: "root", group: "root", path: "/etc/systemd/system/rh-mariadb102-mariadb.service.d", mode: "0755" }
    - { owner: "root", group: "root", path: "/etc/systemd/system/nginx.service.d", mode: "0755" }
    - { owner: "root", group: "root", path: "/etc/systemd/system/php72-php-fpm.service.d", mode: "0755" }

- name:             place systemd override configs
  template:
    src:           "{{ item.template }}"
    dest:          "/etc/systemd/system/{{ item.service }}.service.d/override.conf"
    owner:          root
    group:          root
    mode:           0644
  register:         systemd_overrides
  with_items:
    - { service: "rh-mariadb102-mariadb", template: "systemd_redhat_rh-mariadb102-mariadb_override.conf.j2" }
    - { service: "nginx", template: "systemd_redhat_nginx_override.conf.j2" }
    - { service: "php72-php-fpm", template: "systemd_redhat_php72-php-fpm_override.conf.j2" }

- name:             force systemd to reread configs
  systemd:          daemon_reload=yes
  when:             systemd_folders is changed or systemd_overrides is changed

- name:             template updates.sql
  template:
    src:            updates.sql.j2
    dest:           /root/tmp/updates.sql
    owner:          root
    group:          root
    mode:           0600
  when:             froxlor_check.stat.exists == false

- name:             apply updates.sql
  shell:           "{{ scl_mariadb }} mysql -BN {{ frox_mysql_db }} < /root/tmp/updates.sql"
  when:             froxlor_check.stat.exists == false

- name:             remove unneeded vhost configs
  file:
    path:           "{{ frox_vhostpath }}/{{ item }}"
    state:          absent
  with_items:
    - _default.conf
    - _froxlor.conf

- name:             symlink /etc/devops/www/index.html to docroot for now
  file:
    src:           "/etc/devops/www/index.html"
    dest:          "/var/www/index.html"
    state:          link

- name:            "template /var/www/{{ frox_webpath }}/scripts/froxlor_master_cronjob.php"
  template:
    src:            froxlor_master_cronjob.php.j2
    dest:          "/var/www/{{ frox_webpath }}/scripts/froxlor_master_cronjob.php"
    owner:          froxlocal
    group:          froxlocal
    mode:           0664
    backup:         yes

- name:             force run froxlor cronjob to generate config
  shell:           "php /var/www/{{ frox_webpath }}/scripts/froxlor_master_cronjob.php --force"
  when:             froxlor_check.stat.exists == false
  notify:           restart nginx

- name:             force run froxlor cronjob for letsencrypt
  shell:           "php /var/www/{{ frox_webpath }}/scripts/froxlor_master_cronjob.php --letsencrypt"
  when:             froxlor_check.stat.exists == false and frox_use_ssl == true
  notify:           restart nginx

- name:             force run froxlor cronjob to finalize
  shell:           "php /var/www/{{ frox_webpath }}/scripts/froxlor_master_cronjob.php --force"
  when:             froxlor_check.stat.exists == false
  notify:           restart nginx
