---

- name:             fetch server IP
  shell:            ifconfig | egrep -o '([0-9]{1,3}\.){3}[0-9]{1,3}' | egrep -v '255|10|(127\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3})' | head -n1
  register:         frox_ip
  failed_when:      false
  changed_when:     false
  when:             frox_ip is undefined

- name:             set facts specific to debian-based distros
  set_fact:
    frox_mysql_socket: "/var/run/mysqld/mysqld.sock"

- name:             template /etc/libnss-mysql.cfg
  template:
    src:            libnss-mysql.cfg.j2
    dest:           /etc/libnss-mysql.cfg
    owner:          root
    group:          root
    mode:           0600
    backup:         yes

- name:             template /etc/libnss-mysql-root.cfg
  template:
    src:            libnss-mysql-root.cfg.j2
    dest:           /etc/libnss-mysql-root.cfg
    owner:          root
    group:          root
    mode:           0600
    backup:         yes

- name:             copy /etc/nsswitch.conf
  copy:
    src:            nsswitch.conf
    dest:           /etc/nsswitch.conf
    owner:          root
    group:          root
    mode:           0644
    backup:         yes

- name:             template /etc/nginx/sites-available/_default.conf
  template:
    src:            nginx.default.conf.j2
    dest:           /etc/nginx/sites-available/_default.conf
    owner:          root
    group:          root
    mode:           0664
  notify:           restart nginx

- name:             template /etc/php/7.2/fpm/default.conf
  template:
    src:            php-fpm.default.conf.j2
    dest:           /etc/php/7.2/fpm/default.conf
    owner:          root
    group:          root
    mode:           0664
  notify:           restart php-fpm

- name:             update /etc/php/7.2/fpm/php-fpm.conf to load default.conf
  lineinfile:       dest=/etc/php/7.2/fpm/php-fpm.conf
                    insertafter='^include=/etc/php/7.2/fpm/pool.d/*.conf'
                    line='include=/etc/php/7.2/fpm/default.conf'
  notify:           restart php-fpm

- name:             update service startup scripts
  lineinfile:       dest="/etc/init.d/{{ item.service }}"
                    state=present
                    regexp=^{{ item.key }}
                    line="{{ item.key }}    {{ item.value }}"
                    insertafter=EOF backrefs=yes
  with_items:
    - { service: 'php7.2-fpm', key: '# Required-Start:', value: '$remote_fs $network mysql' }

- name:             template updates.sql
  template:
    src:            updates.sql.j2
    dest:           /root/tmp/updates.sql
    owner:          root
    group:          root
    mode:           0600
  when:             froxlor_check.stat.exists == false

- name:             apply updates.sql
  shell:           "mysql -BN {{ frox_mysql_db }} < /root/tmp/updates.sql"
  when:             froxlor_check.stat.exists == false

- name:             remove our froxlor vhost config
  file:
    path:           "{{ frox_vhostpath }}/_froxlor.conf"
    state:          absent

- name:             force run froxlor cronjob to finalize
  shell:            php /var/www/froxlor/scripts/froxlor_master_cronjob.php --force
  when:             froxlor_check.stat.exists == false
  notify:           restart nginx
