---

- name:             fetch server IP
  shell:            ifconfig | egrep -o '([0-9]{1,3}\.){3}[0-9]{1,3}' | egrep -v '255|10|(127\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3})' | head -n1
  register:         frox_ip
  failed_when:      false
  changed_when:     false

- name:             set facts specific to debian-based distros
  set_fact:
    frox_mysql_socket: "/var/run/mysqld/mysqld.sock"

- name:             create /etc/nginx/conf-enabled/ when ssl is enabled
  file:             path=/etc/nginx/conf-enabled/ state=directory owner=root group=root mode=0755
  when:             frox_use_ssl == true

- name:             template /etc/nginx/conf-enabled/acme.conf when ssl is enabled
  template:
    src:            acme.conf.j2
    dest:           /etc/nginx/conf-enabled/acme.conf
    owner:          root
    group:          root
    mode:           0644
  when:             frox_use_ssl == true

- name:             template /etc/libnss-mysql.cfg
  template:
    src:            libnss-mysql.cfg.j2
    dest:           /etc/libnss-mysql.cfg
    owner:          root
    group:          root
    mode:           0600
    backup:         yes

- name:             template /etc/libnss-mysql-root.cfg
  template:
    src:            libnss-mysql-root.cfg.j2
    dest:           /etc/libnss-mysql-root.cfg
    owner:          root
    group:          root
    mode:           0600
    backup:         yes

- name:             copy /etc/nsswitch.conf
  copy:
    src:            nsswitch.conf
    dest:           /etc/nsswitch.conf
    owner:          root
    group:          root
    mode:           0644
    backup:         yes

- name:             template /etc/nginx/sites-available/_default.conf
  template:
    src:            nginx.default.conf.j2
    dest:           /etc/nginx/sites-available/_default.conf
    owner:          root
    group:          root
    mode:           0664
  notify:           restart nginx

- name:             template /etc/php/7.2/fpm/default.conf
  template:
    src:            php-fpm.default.conf.j2
    dest:           /etc/php/7.2/fpm/default.conf
    owner:          root
    group:          root
    mode:           0664
  notify:           restart php-fpm

- name:             update /etc/php/7.2/fpm/php-fpm.conf to load default.conf
  lineinfile:       dest=/etc/php/7.2/fpm/php-fpm.conf
                    insertafter='^include=/etc/php/7.2/fpm/pool.d/*.conf'
                    line='include=/etc/php/7.2/fpm/default.conf'
                    state=present
  notify:           restart php-fpm

- name:             update service startup scripts
  lineinfile:       dest="/etc/init.d/{{ item.service }}"
                    state=present
                    regexp=^{{ item.key }}
                    line="{{ item.key }}    {{ item.value }}"
                    insertafter=EOF backrefs=yes
  with_items:
    - { service: 'php7.2-fpm', key: '# Required-Start:', value: '$remote_fs $network mysql nscd' }
    - { service: 'nscd', key: '# Required-Start:', value: '$remote_fs $network mysql' }

- name:             create systemd folders
  file:
    path:  "{{ item.path }}"
    state: directory
    owner: "{{ item.owner }}"
    group: "{{ item.group }}"
    mode:  "{{ item.mode }}"
  with_items:
    - { owner: "root", group: "root", path: "/etc/systemd/system/nginx.service.d", mode: "0755" }
    - { owner: "root", group: "root", path: "/etc/systemd/system/php7.2-fpm.service.d", mode: "0755" }
    - { owner: "root", group: "root", path: "/etc/systemd/system/nscd.service.d", mode: "0755" }

- name:             place systemd override configs
  template:
    src:           "{{ item.template }}"
    dest:          "/etc/systemd/system/{{ item.service }}.service.d/override.conf"
    owner:          root
    group:          root
    mode:           0644
  with_items:
    - { service: "nginx", template: "systemd_debian_nginx_override.conf.j2" }
    - { service: "php7.2-fpm", template: "systemd_debian_php7.2-fpm_override.conf.j2" }
    - { service: "nscd", template: "systemd_debian_nscd_override.conf.j2" }

- name:             template updates.sql
  template:
    src:            updates.sql.j2
    dest:           /root/tmp/updates.sql
    owner:          root
    group:          root
    mode:           0600
  when:             froxlor_check.stat.exists == false

- name:             apply updates.sql
  shell:           "mysql -BN {{ frox_mysql_db }} < /root/tmp/updates.sql"
  when:             froxlor_check.stat.exists == false

- name:             remove our froxlor vhost config
  file:
    path:           "{{ frox_vhostpath }}/_froxlor.conf"
    state:          absent

- name:             template /var/www/froxlor/scripts/froxlor_master_cronjob.php
  template:
    src:            froxlor_master_cronjob.php.j2
    dest:           /var/www/froxlor/scripts/froxlor_master_cronjob.php
    owner:          froxlocal
    group:          froxlocal
    mode:           0664
    backup:         yes

- name:             force run froxlor cronjob to finalize
  shell:            php /var/www/froxlor/scripts/froxlor_master_cronjob.php --force
  when:             froxlor_check.stat.exists == false
  notify:           restart nginx
