---

- name:             template /etc/libnss-mysql.cfg
  template:
    src:            libnss-mysql.cfg.j2
    dest:           /etc/libnss-mysql.cfg
    owner:          root
    group:          root
    mode:           0600
    backup:         yes
  notify:           restart nscd

- name:             template /etc/libnss-mysql-root.cfg
  template:
    src:            libnss-mysql-root.cfg.j2
    dest:           /etc/libnss-mysql-root.cfg
    owner:          root
    group:          root
    mode:           0600
    backup:         yes
  notify:           restart nscd

- name:             copy /etc/nsswitch.conf
  copy:
    src:            nsswitch.conf
    dest:           /etc/nsswitch.conf
    owner:          root
    group:          root
    mode:           0644
    backup:         yes
  notify:           restart nscd

- name:             update service startup scripts
  lineinfile:       dest="/etc/init.d/{{ item.service }}"
                    state=present
                    regexp=^{{ item.key }}
                    line="{{ item.key }}    {{ item.value }}"
                    insertafter=EOF backrefs=yes
  with_items:
    - { service: 'php7.2-fpm', key: '# Required-Start:', value: '$remote_fs $network mysql nscd' }
    - { service: 'nscd', key: '# Required-Start:', value: '$remote_fs $syslog $network mysql' }

- name:             template updates.sql
  template:
    src:            updates.sql.j2
    dest:           /root/tmp/updates.sql
    owner:          root
    group:          root
    mode:           0600
  when:             froxlor_check.stat.exists == false

- name:             apply updates.sql
  mysql_db:
    name:          "{{ frox_mysql_db }}"
    state:          import
    target:         /root/tmp/updates.sql
  when:             froxlor_check.stat.exists == false

- name:             remove our froxlor vhost config
  file:
    path:           /etc/nginx/sites-enabled/_froxlor.conf
    state:          absent

- name:             force run froxlor cronjob to finalize
  shell:            php /var/www/froxlor/scripts/froxlor_master_cronjob.php --force
  when:             froxlor_check.stat.exists == false
  notify:           restart nginx

