---

- name:             install | Clone netdata to /usr/local/src
  git:              repo="https://github.com/firehol/netdata"
                    dest="/usr/local/src/netdata"
                    depth=1
  register:         netdata_clone

- name:             install | Run netdata installer
  shell:            ./netdata-installer.sh --dont-wait 1>~/tmp/netdata-installer.log
                    chdir=/usr/local/src/netdata
                    creates=/usr/sbin/netdata
  register:         netdata_install
  notify:
    - restart netdata

- name:             update | Run netdata updater
  shell:            ./netdata-updater.sh 1>~/tmp/netdata-updater.log
                    chdir=/usr/local/src/netdata
  register:         netdata_update
  when:
    - netdata_clone is changed
    - netdata_install is not changed
  notify:
    - restart netdata

#- name:             config | Configuring Netdata
#  notify
#    - restart netdata
# todo: lineinfile bind ip to 127.0.0.1

- name:             config | Setup auto-update cronjob
  file:             path=/etc/cron.daily/netdata-updater
                    src=/usr/local/src/netdata/netdata-updater.sh
                    state=link
