---

- name:             restart filebeat
  service:          name={{ service_filebeat_name }} state=restarted enabled=yes

- name:             restart metricbeat
  service:          name={{ service_metricbeat_name }} state=restarted enabled=yes

- name:             restart auditbeat
  service:          name={{ service_auditbeat_name }} state=restarted enabled=yes

- name:             restart packetbeat
  service:          name={{ service_packetbeat_name }} state=restarted enabled=yes
