---

- name:             restart carbon-cache
  service:          name=graphite_carbon_cache state=restarted enabled=yes

- name:             restart uwsgi
  service:          name=uwsgi state=restarted enabled=yes

- name:             restart grafana
  service:          name=grafana-server state=restarted enabled=yes

- name:             reload nginx
  service:          name=nginx state=reloaded
