---

- name:             get stat into of status file
  stat:             path=/root/._ansible
  register:         update_statuscheck
  changed_when:     false

- include_tasks:    debian-based.yml
  when:             ansible_distribution == "Ubuntu" or ansible_distribution == "Debian"

- include_tasks:    redhat-based.yml
  when:             ansible_distribution == "CloudLinux"

