---

- name:             enable predefined repositories
  shell:            yum-config-manager --enable {{ item }}
  with_items:       '{{ enable_repos }}'
  when:             enable_repos is defined

- name:             enable EPEL repository
  yum:              name={{ item }} state=present
  with_items:       '{{ install_epel }}'

- name:             install some tools
  yum:              name={{ item }} state=present
  with_items:       '{{ install_tools }}'
  when:             install_tools is defined

- name:             install development packages
  yum:              name={{ item }} state=present
  with_items:       '{{ install_dev }}'
  when:             install_dev is defined

- name:             install python packages thru pip
  pip:              name={{ item }} state=present umask=0022
  with_items:       '{{ install_dev_pip }}'
  when:             install_dev_pip is defined

- name:             install mongodb specific packages
  yum:              name=python-pymongo state=present
  when:             inventory_hostname in groups['mongodb']|default([])

- name:             remove unwanted packages
  yum:              name={{ item }} state=absent
  with_items:       '{{ uninstall_unwanted }}'
  when:             uninstall_unwanted is defined

- name:             upgrade all packages
  yum:              name='*' state=latest

- name:             place /usr/share/git-core/contrib/git-prompt.sh
  copy:             dest=/usr/share/git-core/contrib/git-prompt.sh src=git-prompt.sh mode=0755
  when:             ansible_distribution == "CloudLinux" or ansible_distribution == "CentOS"

