---

- name:             (re)create initial conf.d/client.json
  template:         dest=/etc/sensu/conf.d/client.json src=client.json
                    owner=sensu group=sensu mode=0600
  when:             sensu_install is changed

- name:             install default sensu plugins
  shell:           "sensu-install -p {{ item }}
                    chdir=/opt/sensu/embedded/bin/
                    creates=/opt/sensu/embedded/lib/ruby/gems/2.4.0/gems/sensu-plugins-{{ item }}-*/"
  with_items:
    - "{{ sensu_default_plugins }}"

- name:             enable + start sensu-client
  service:          name={{ service_sensu_client }} enabled=yes state=started
  when:             sensu_install is changed

