---

- name:             install default sensu plugins
  shell:           "sensu-install -p {{ item }}
                    chdir=/opt/sensu/embedded/bin/
                    creates=/opt/sensu/embedded/lib/ruby/gems/2.4.0/gems/sensu-plugins-{{ item }}-*/"
  with_items:
    - "{{ sensu_default_plugins }}"

