---

- name:             install uchiwa package
  apt:              name={{ item }} state=present
  with_items:
    - "{{ pkgs_uchiwa }}"
  register:         uchiwa_install

- name:             (re)create uchiwa.json
  template:         dest=/etc/sensu/uchiwa.json src=uchiwa.json
                    owner=uchiwa group=uchiwa mode=0600

- name:             enable + start uchiwa
  service:          name={{ service_sensu_uchiwa }} enabled=yes state=started
  when:             uchiwa_install is changed

- name:             touch uchiwa in /root/stat_services.d
  file:             path=/root/stat_services.d/uchiwa state=touch
  changed_when:     false
