---

- name:             install uchiwa package
  apt:              name={{ item }} state=present
  with_items:
    - "{{ pkgs_uchiwa }}"
  register:         uchiwa_install

- name:             touch uchiwa in /root/stat_services.d
  file:             path=/root/stat_services.d/uchiwa state=touch
  changed_when:     false
