---

- include_vars:     "{{ ansible_distribution }}.yml"

- name:             install python packages
  package:          name={{ item }} state=present
  with_items:
    - "{{ pkgs_python }}"
  when:             pkgs_python is defined
