---

- name:             update kibana config
  lineinfile:       dest=/etc/kibana/kibana.yml
                    state=present
                    regexp=^{{ item.search }}
                    line="{{ item.replace }}"
                    insertafter=EOF backrefs=yes
  with_items:
    - { search: '#server.basePath: ""', replace: 'server.basePath: "/kibana"' }
    - { search: '#elasticsearch.username: "user"', replace: 'elasticsearch.username: "kibana"' }
    - { search: '#elasticsearch.password: "pass"', replace: 'elasticsearch.password: "{{ xpack_passwd_kibana }}"' }
  notify:
    - restart kibana

- name:             start and enable kibana
  service:          name=kibana state=started enabled=yes
