---

- include_tasks:    kibana-install_debian-based.yml
  when:             pkgs_kibana is defined and (ansible_distribution == "Ubuntu" or ansible_distribution == "Debian")

- include_tasks:    kibana-install_general.yml

