---

- name:            "enable filebeat module: system (default)"
  shell:            filebeat modules enable system
  register:         filebeat_system
  changed_when:     filebeat_system.stdout == "Enabled system"
  notify:           restart filebeat

- name:             (re)run filebeat setup if required
  shell:            filebeat setup -E output.logstash.enabled=false -E 'output.elasticsearch.hosts=["localhost:9200"]'
  notify:           restart filebeat
  when:
    - filebeat_system.stdout == "Enabled system"
    - "'monitor' in group_names"
    - filebeat_config_update is changed

- name:             (re)run metricbeat setup if required
  shell:            metricbeat setup -E output.logstash.enabled=false -E 'output.elasticsearch.hosts=["localhost:9200"]'
  notify:           restart metricbeat
  when:
    - "'monitor' in group_names"
    - metricbeat_config_update is changed
