---

- include_tasks:    beats-install_debian-based.yml
  when:             pkgs_beats is defined and (ansible_distribution == "Ubuntu" or ansible_distribution == "Debian")

- include_tasks:    beats-configure_general.yml

#- include_tasks:    beats-configure_xpack.yml
#  when:             elk_stack_use_xpack

- include_tasks:    beats-modules_setup.yml
