---

- include_tasks:    beats-install_debian-based.yml
  when:             pkgs_beats is defined and (ansible_distribution == "Ubuntu" or ansible_distribution == "Debian")

- include_tasks:    beats-install_general.yml

