---

- name:            "download phpmyadmin {{ phpmyadmin_version }}"
  get_url:          url="https://files.phpmyadmin.net/phpMyAdmin/{{ phpmyadmin_version }}/phpMyAdmin-{{ phpmyadmin_version }}-english.tar.gz"
                    dest="/root/tmp/phpMyAdmin-{{ phpmyadmin_version }}-english.tar.gz"
  register:         myadmin_download

- name:             check for /usr/local/src/phpMyAdmin
  stat:             path=/usr/local/src/phpMyAdmin
  register:         check_path

- name:             unpack phpmyadmin to /usr/local/src
  unarchive:        src="/root/tmp/phpMyAdmin-{{ phpmyadmin_version }}-english.tar.gz"
                    dest=/usr/local/src
                    remote_src=yes
  when:             (myadmin_download is changed) and (check_path.stat.exists == false)

- name:            "check for /usr/local/src/phpMyAdmin-{{ phpmyadmin_version }}-english"
  stat:             path="/usr/local/src/phpMyAdmin-{{ phpmyadmin_version }}-english"
  register:         check_unpack_path

- name:            "rename /usr/local/src/phpMyAdmin-{{ phpmyadmin_version }}-english to phpMyAdmin"
  command:         "mv /usr/local/src/phpMyAdmin-{{ phpmyadmin_version }}-english/ /usr/local/src/phpMyAdmin/
                    creates=/usr/local/src/phpMyAdmin/index.php"
  when:             (myadmin_download is changed) and (check_unpack_path.stat.exists == true)

- name:             copy config.sample.inc.php to config.inc.php
  copy:             src=/usr/local/src/phpMyAdmin/config.sample.inc.php
                    dest=/usr/local/src/phpMyAdmin/config.inc.php
                    remote_src=yes
  when:             myadmin_download is changed

- name:             set $cfg['blowfish_secret']
  replace:          path=/usr/local/src/phpMyAdmin/config.inc.php
                    regexp="^\$cfg\['blowfish_secret(.*)?$"
                    replace="$cfg['blowfish_secret'] = 'thisisalongstringthatissupposetobeasecretsoshhhhdonttell';"

- name:             set http user/group vars for redhat-based
  set_fact:
    httpd_user:  nginx
    httpd_group: nginx
  when:             ansible_distribution == "CentOS" or ansible_distribution == "RedHat"

- name:             create tmp folder nginx can write in
  file:             path=/usr/local/src/phpMyAdmin/tmp
                    state=directory
                    mode=0700
                    owner="{{ httpd_user }}"
                    group="{{ httpd_group }}"

- name:            "symlink phpMyAdmin to {{ phpmyadmin_webroot }}"
  file:             src=/usr/local/src/phpMyAdmin
                    dest="/usr/local/src/{{ phpmyadmin_webroot }}"
                    state=link
  when:             myadmin_download is changed
