---

- name:             ensure anonymous users are not in the database
  mysql_user:       name="" host="{{ item }}" state=absent
  with_items:
    - localhost
    - 127.0.0.1
    - ::1
    - "%"
  when:             deb_mariadb_install_packages is defined and deb_mariadb_install_packages.changed

- name:             Remove MariaDB test database.
  mysql_db:         name='test' state=absent

- name:             Disallow root login remotely
  command:          "{{ scl_mariadb }} mysql -NBe \"{{ item }}\""
  with_items:
    - DELETE FROM mysql.user WHERE User='root' AND Host NOT IN ('localhost', '127.0.0.1','::1')
  changed_when:     false

- name:             Get list of hosts for the root user.
  command:         "{{ scl_mariadb }} mysql -NBe \"SELECT Host FROM mysql.user WHERE User = 'root' ORDER BY (Host='localhost') ASC\""
  register:         mysql_root_hosts
  changed_when:     false

# Note: We do not use mysql_user for this operation, as it doesn't always update
# the root password correctly. See: https://goo.gl/MSOejW
# no_log since password will be in output, beware!
#
- name:             Update MariaDB root password for localhost root account.
  shell:           "{{ scl_mariadb }} mysql -NBe \"SET PASSWORD FOR 'root'@'{{ item }}' = PASSWORD('{{ mariadb_root_password }}');\""
  with_items:
    - "{{ mysql_root_hosts.stdout_lines }}"
  when:             deb_mariadb_install_packages is defined and deb_mariadb_install_packages.changed
  no_log:           true

- name:             Allow root to login on localhost
  shell:           "{{ scl_mariadb }} mysql --password='{{mariadb_root_password }}' -NBe \"GRANT ALL PRIVILEGES on *.* to 'root'@'localhost' IDENTIFIED BY '{{ mariadb_root_password}}'; FLUSH PRIVILEGES;\""
  when:             deb_mariadb_install_packages is defined and deb_mariadb_install_packages.changed
  no_log:           true

# Has to be after the root password assignment, for idempotency.
- name:             Copy .my.cnf file with root password credentials.
  template:
    src: "user-my.cnf.j2"
    dest: "/root/.my.cnf"
    owner: root
    group: root
    mode: 0600
  when:             deb_mariadb_install_packages is defined and deb_mariadb_install_packages.changed

- name:             (re)configure server cnf
  template:
    src:  "{{ cnf_template }}"
    dest: "{{ cnf_path }}"
    owner: root
    group: root
    mode: 0644
  notify:           restart mariadb
