---

- name:             reload nginx
  service:          name=nginx state=reloaded

- name:             restart sensu-client
  service:          name=sensu-client enabled=yes state=restarted

- name:             restart sensu-server
  service:          name=sensu-server enabled=yes state=restarted

- name:             restart sensu-api
  service:          name=sensu-api enabled=yes state=restarted
