---

- include_vars:     "{{ ansible_distribution }}.yml"

- name:             install proftpd packages
  package:          name={{ item }} state=present
  notify:           start proftpd
  with_items:
    - "{{ pkgs_proftpd }}"

- name:             Allow ftp and PASV ports through UFW
  ufw:              rule=allow port={{ item }} proto=tcp
  with_items:
    - "{{ ftp_ports }}"
  when:             ansible_distribution == "Ubuntu" or ansible_distribution == "Debian"

- name:             Allow ftp traffic through Firewalld
  firewalld:        service={{ item }} permanent=true state=enabled
  notify:           reload firewalld
  with_items:
    - "{{ ftp_ports }}"
  when:             ansible_distribution == "CentOS" or ansible_distribution == "RedHat"

- name:             Allow PASV traffic through Firewalld
  firewalld:        port={{ item }} permanent=true state=enabled
  notify:           reload firewalld
  with_items:
    - "{{ ftp_ports_pasv }}"
  when:             ansible_distribution == "CentOS" or ansible_distribution == "RedHat"
