---

service_phpfpm_name: php7.2-fpm
service_proftpd_name: proftpd

# Change this when not testing!
# Overwrite with group_vars or host_vars
mariadb_root_password: "foo"

frox_version:      0.9.39.5
frox_sha256sum:    1fd245d459346a43ffab1179b64b7215bc2727235fe3fcfec569a195e1345599

frox_webpath:      froxlor

frox_mysql_db:     froxlor
frox_mysql_user:   froxlor
frox_mysql_pass:   froxlor

frox_admin_user:   admin
frox_admin_pass:   admin

frox_httpd:        nginx
frox_httpd_user:   www-data
frox_httpd_group:  www-data

frox_lang:         english

frox_use_ssl:      false

frox_vhostpath:    /etc/nginx/sites-enabled

frox_mysql_socket: "/var/run/mysqld/mysqld.sock"

frox_support_pkgs_debian:
  - libnss-mysql-bg
  - nscd

frox_support_pkgs_redhat:
  - libnss-mysql
  - nscd

frox_dont_backup:
  - cache/wp-rocket/

frox_dont_log:
  - ~*dontlogme.php
  - ~*example.php
  - ~*favicon.ico

# Reconfigure default settings
frox_opcache_revalidate_freq:         '0'
frox_opcache_validate_timestamps:     'false'
frox_opcache_accelerated_files:       '100000'
frox_opcache_memory_consumption:      '512'
frox_opcache_interned_strings_buffer: '32'

frox_php_max_execution_time:          '60'
frox_php_memory_limit:                '128M'
frox_php_post_max_size:               '16M'
frox_php_upload_max_filesize:         '32M'

frox_fpm_pm:                          'dynamic'
frox_fpm_pm_max_children:             '5'
frox_fpm_pm_start_servers:            '3'
frox_fpm_pm_min_spare_servers:        '2'
frox_fpm_pm_max_spare_servers:        '4'
frox_fpm_pm_max_requests:             '200'

frox_vhost_config_name:               'Froxlor Vhost Config'
frox_noreply_email:                   'example@example.com'
frox_admin_email:                     'example@example.com'
frox_admin_name:                      'Froxlor Administrator'

proftpd_user:      proftpd
proftpd_group:     nogroup
proftpd_modules:   /usr/lib/proftpd

phpmyadmin_webroot: database
