---

- name:             install fail2ban
  package:          name={{ item }} state=present
  with_items:
    - "{{ pkgs_fail2ban }}"

- name:             copy fail2ban.conf
  copy:             src=fail2ban.conf dest=/etc/fail2ban/fail2ban.conf force=yes owner=root group=root mode=0644
  notify:           restart fail2ban

- name:             copy jail.conf
  copy:             src=jail.redhat.conf dest=/etc/fail2ban/jail.conf force=yes owner=root group=root mode=0644
  notify:           restart fail2ban
  when:             ansible_distribution == "CentOS" or ansible_distribution == "RedHat"

- name:             copy jail.conf
  copy:             src=jail.debian.conf dest=/etc/fail2ban/jail.conf force=yes owner=root group=root mode=0644
  notify:           restart fail2ban
  when:             ansible_distribution == "Ubuntu" or ansible_distribution == "Debian"

- name:             copy action.d/ufw-ssh.conf
  copy:             src=ufw-ssh.conf dest=/etc/fail2ban/action.d/ufw-ssh.conf force=yes owner=root group=root mode=0644
  notify:           restart fail2ban
  when:             ansible_distribution == "Ubuntu" or ansible_distribution == "Debian"

