---

- include_tasks:    graphite-install_general.yml

- include_tasks:    graphite-install_debian-based.yml
  when:             pkgs_uwsgi is defined and (ansible_distribution == "Ubuntu" or ansible_distribution == "Debian")

- include_tasks:    graphite-setup_general.yml
