---

- include_vars:     "{{ ansible_distribution }}.yml"

- name:             install imagemagick packages
  package:          name={{ item }} state=present
  with_items:
    - "{{ pkgs_imagemagick }}"
  when:             pkgs_imagemagick is defined
