---

- name:             place apt wrapper
  copy:             src=apt-wrapper
                    dest=/usr/local/sbin/apt
                    owner=root group=root mode=0755
  when:             ansible_distribution == "Ubuntu" or ansible_distribution == "Debian"

- name:             place apt-get wrapper
  copy:             src=apt-get-wrapper
                    dest=/usr/local/sbin/apt-get
                    owner=root group=root mode=0755
  when:             ansible_distribution == "Ubuntu" or ansible_distribution == "Debian"

- name:             create 700 directories in ~root
  file:             path=/root/{{ item }} state=directory mode=0700
  with_items:       '{{ root_folders }}'
  when:             root_folders is defined

- name:             create directories in /opt + /root/cache
  file:             path={{ item }} state=directory mode=0755
  with_items:       '{{ default_folders }}'
  when:             default_folders is defined

- name:             set FQDN - localhost
  lineinfile:       dest=/etc/hosts regexp='^127\.0\.0\.1' line='127.0.0.1 localhost' owner=root group=root mode=0644

- name:             set example.com FQDN - hostname
  lineinfile:       dest=/etc/hosts insertafter='^127\.0\.0\.1' line='127.0.1.1 {{ ansible_hostname }}.example.com {{ ansible_hostname }} netdata.me' owner=root group=root mode=0644

- name:             remove any leftover 127.0.1.1 entries from pre-netdata
  lineinfile:       dest=/etc/hosts state=absent regexp='^127\.0\.1\.1 {{ ansible_hostname }} {{ ansible_hostname }}'

- name:             remove any leftover 127.0.1.1 entries from pre-netdata
  lineinfile:       dest=/etc/hosts state=absent regexp='^127\.0\.1\.1 {{ ansible_hostname }}.example.com {{ ansible_hostname }}$'

- name:             remove any leftover 127.0.1.1 entries from post-netdata
  lineinfile:       dest=/etc/hosts state=absent regexp='^127\.0\.1\.1 {{ ansible_hostname }} {{ ansible_hostname }} netdata.me'

- name:             set default editor (debian based)
  command:          update-alternatives --set editor {{ alt.editor }}
  register:         common_alt_editor
  changed_when:     '"using" in common_alt_editor.stdout'
  when:             ansible_distribution == "Ubuntu" or ansible_distribution == "Debian"

- name:             set default editor (redhat based)
  copy:             src=nano.sh
                    dest=/etc/profile.d/nano.sh
                    owner=root group=root mode=0644
  when:             ansible_distribution == "CloudLinux" or ansible_distribution == "CentOS"

- name:             link ack to ack-grep
  file:             path=/usr/local/bin/ack src=/usr/bin/ack-grep state=link force=yes

- name:             place /etc/prompt.bash
  copy:             dest=/etc/prompt.bash src=prompt.bash mode=0644

- name:             place /etc/checkrestart.blacklist
  copy:             dest=/etc/checkrestart.blacklist src=checkrestart.blacklist mode=0644
  when:             ansible_distribution == "Ubuntu" or ansible_distribution == "Debian"

- name:             fix stock sshd_config in trusty (add EOF..)
  shell:            'test "$( tail -c1 /etc/ssh/sshd_config )" = "" || echo >> /etc/ssh/sshd_config'
  changed_when:     false

- name:             update ssh parameters
  lineinfile:       dest=/etc/ssh/sshd_config
                    state=present
                    regexp=^{{ item.key }}
                    line="{{ item.key }} {{ item.value }}"
                    insertafter=EOF
  with_items:
    - { key: 'PermitRootLogin', value: 'no' }
    - { key: 'LoginGraceTime', value: '120' }
    - { key: 'TCPKeepAlive', value: 'yes' }
    - { key: 'X11Forwarding', value: 'yes' }
    - { key: 'ClientAliveInterval', value: '60' }
  notify:
    - restart ssh

- name:             Set firewall rules for web traffic and SSH
  ufw:              rule=allow port={{ item }} proto=tcp
  with_items:
    - ssh
    - http
    - https
  when:             ansible_distribution == "Ubuntu" or ansible_distribution == "Debian"

- name:             Allow internal network on VMs
  ufw:              rule=allow src={{ item }}
  with_items:
    - 172.28.128.0/24
  when:             ansible_distribution == "Ubuntu" or ansible_distribution == "Debian" and ansible_virtualization_role == "guest"

- name:             Deny everything and enable UFW
  ufw:              state=enabled policy=deny
  when:             ansible_distribution == "Ubuntu" or ansible_distribution == "Debian"
