---

- include_vars:     "{{ ansible_distribution }}.yml"

- include_tasks:    general.yml

- include_tasks:    debian-based.yml
  when:             ansible_distribution == "Ubuntu" or ansible_distribution == "Debian"

- include_tasks:    redhat-based.yml
  when:             ansible_distribution == "CentOS" or ansible_distribution == "RedHat"
