---

- name:             enable predefined repositories
  shell:            yum-config-manager --enable {{ item }}
  with_items:       '{{ enable_repos }}'
  when:             enable_repos is defined

- name:             enable EPEL repository
  yum:              name={{ item }} state=present
  with_items:       '{{ install_epel }}'

- name:             set default editor
  copy:             src=nano.sh
                    dest=/etc/profile.d/nano.sh
                    owner=root group=root mode=0644

- name:             Set SELinux to permissive
  selinux:          policy=targeted state=permissive
