---

- name:             force java to ipv4 and setup jmx profiling
  lineinfile:       dest=/etc/default/elasticsearch
                    state=present
                    line="{{ item.key }}={{ item.value }}"
  with_items:
    - { key: 'ES_JAVA_OPTS', value: '"-Djava.net.preferIPv4Stack=true"' }
    - { key: 'ES_JAVA_OPTS', value: '"$ES_JAVA_OPTS -Dcom.sun.management.jmxremote.port=6789"' }
    - { key: 'ES_JAVA_OPTS', value: '"$ES_JAVA_OPTS -Dcom.sun.management.jmxremote.ssl=false"' }
    - { key: 'ES_JAVA_OPTS', value: '"$ES_JAVA_OPTS -Dcom.sun.management.jmxremote.authenticate=false"' }
    - { key: 'ES_JAVA_OPTS', value: '"$ES_JAVA_OPTS -Djava.rmi.server.hostname=172.28.128.3"' }
  notify:
    - restart elasticsearch

- name:             start and enable elasticsearch
  service:          name=elasticsearch state=started enabled=yes

- name:             start and enable elasticsearch-head
  service:          name=elasticsearch-head state=started enabled=yes
