---

- name:             check if xpack was installed allready
  stat:             path=/usr/share/elasticsearch/bin/x-pack/x-pack-env
  register:         es_xpack_check
  changed_when:     false

- name:             ensure elasticsearch is stopped before installing xpack
  service:          name=elasticsearch state=stopped enabled=yes
  when:             es_xpack_check.stat.exists == false

- name:             install xpack plugin for elasticsearch
  shell:            bin/elasticsearch-plugin install --batch x-pack
                    chdir=/usr/share/elasticsearch
                    creates=/usr/share/elasticsearch/bin/x-pack/x-pack-env
  register:         es_xpack_install

- name:             ensure elasticsearch is started again for the next step
  service:          name=elasticsearch state=started enabled=yes
  when:             es_xpack_install is changed

- name:             wait for elasticsearch to finish starting
  wait_for:         port={{item}} delay=10 connect_timeout=10
  with_items:
    - 9200
    - 9300
  when:             es_xpack_install is changed

- name:             generate system passwords if xpack is newly installed
  shell:            bin/x-pack/setup-passwords auto --batch > /root/.xpack.auth
                    chdir=/usr/share/elasticsearch
                    creates=/root/.xpack.auth
