---

- include_tasks:    es-install_debian-based.yml
  when:             pkgs_elasticsearch is defined and (ansible_distribution == "Ubuntu" or ansible_distribution == "Debian")

- include_tasks:    es-install_general.yml
