---

- name:             touch status file
  file:             path=/root/._ansible state=touch
  changed_when:     false

# Currently broken in ansible 2.4.x, registers server but fails regardless due to user/pass trying to be used with key
#- name:             register license with cloudlinux servers
#  rhn_register:     state=present activationkey="{{ cloudlinux_license }}" channels=cloudlinux-base

# Workaround for the above
- name:             enable repo cloudlinux-base
  shell:            yum install rhn-setup --enablerepo=cloudlinux-base
  changed_when:     false

- name:             register license with cloudlinux servers
  shell:           "rhnreg_ks --activationkey={{ cloudlinux_license }} --force
                    creates=/etc/sysconfig/rhn/systemid"
# /Workaround

- name:             enable predefined repositories
  shell:            yum-config-manager --enable {{ item }}
  with_items:       '{{ enable_repos }}'

- name:             install some tools
  yum:              name={{ item }} state=present
  with_items:       '{{ install_init }}'

- name:             install some python tools with pip
  pip:              name={{ item }} state=present
  with_items:       '{{ install_pip_init }}'

- name:             add default non root user called cloudlinux
  user:             name=cloudlinux shell=/bin/bash

- name:             set cloudlinux user password
  shell:            usermod -p '{{ my_password2 }}' cloudlinux
  when:             my_password2 is defined and my_password2_vm is not defined

- name:             set cloudlinux user password
  shell:            usermod -p `python -c "from passlib.hash import sha512_crypt; import getpass; print(sha512_crypt.using(rounds=5000).hash('{{ my_password2 }}'))"` cloudlinux
  when:             my_password2 is defined and my_password2_vm is defined

- name:             set sudo passwd_tries to 1 (default=3)
  copy:             src=passwd_tries dest=/etc/sudoers.d/passwd_tries mode=0440 validate='visudo -cf %s'

#- name:             install squid-deb-proxy-client
#  apt:              name=squid-deb-proxy-client state=present
