---

# take inventory
# always include this when using tags!
- name:             Gather facts and create dynamic groups before we start
  hosts:            all
  become:           true
  become_user:      root
  gather_facts:     true
  tags:             gather
  tasks:
     - group_by:     key={{ ansible_distribution }}
       changed_when: false
     - group_by:     key={{ ansible_distribution }}_{{ ansible_distribution_release }}
       changed_when: false

# go time
- name:             Running Plays now
  hosts:            all
  become:           true
  become_user:      root
  gather_facts:     false

# base
- import_playbook: ../roles/common.yml
  tags: [common, init]
  vars:
    targets: all

- import_playbook: ../roles/etckeeper.yml
  tags: [etckeeper, init]
  vars:
    targets: all

- import_playbook: ../roles/update.yml
  tags: [update, init]
  vars:
    targets: all

- import_playbook: ../roles/ntp.yml
  tags: [ntp, init]
  vars:
    targets: all

- import_playbook: ../roles/repos.yml
  tags: [repos, init]
  vars:
    targets: all

# dev
- import_playbook: ../roles/ruby.yml
  tags: [ruby, dev]
  vars:
    targets: ruby

- import_playbook: ../roles/python.yml
  tags: [python, dev]
  vars:
    targets: python

- import_playbook: ../roles/dotnet.yml
  tags: [dotnet, dev]
  vars:
    targets: dotnet

- import_playbook: ../roles/nodejs.yml
  tags: [nodejs, dev]
  vars:
    targets: nodejs

- import_playbook: ../roles/libav.yml
  tags: [libav, dev]
  vars:
    targets: libraries

- import_playbook: ../roles/imagemagick.yml
  tags: [imagemagick, dev]
  vars:
    targets: libraries

# services
- import_playbook: ../roles/nginx.yml
  tags: [nginx, services]
  vars:
    targets: all

- import_playbook: ../roles/mariadb.yml
  tags: [mariadb, services]
  vars:
    targets: all

- import_playbook: ../roles/php-fpm.yml
  tags: [php-fpm, services]
  vars:
    targets: all

# general user setup
- import_playbook: ../roles/setup-user.yml
  tags: [users, user-root]
  vars:
    targets:  all
    user:   root
    home:   /root
    keygen: false

- import_playbook: ../roles/setup-user.yml
  tags: [users, user-ubuntu]
  vars:
    targets:  Ubuntu
    user:   ubuntu
    home:   /home/ubuntu
    keygen: false

- import_playbook: ../roles/setup-user.yml
  tags: [users, user-vagrant]
  vars:
    targets:  vm-ubuntu
    user:   vagrant
    home:   /home/vagrant
    keygen: false

